"""Balance and tuning constants for simulation systems."""

# Population dynamics
POPULATION_BASE_BIRTHS = 0.03
POPULATION_BASE_DEATHS = 0.02
EDU_FERTILITY_REDUCTION = 0.6
HEALTH_MORTALITY_REDUCTION = 0.6
POLLUTION_MORTALITY_PENALTY = 0.7
HOUSING_GROWTH_BONUS = 0.2
MIN_OVER_CAPACITY_FACTOR = 0.5

# Population indices targets
HEALTH_TARGET_BASE = 40
HEALTH_PER_HOUSING_LEVEL = 6
HEALTH_PER_POWER_LEVEL = 4
HEALTH_PER_RESEARCH_LEVEL = 2
HEALTH_POLLUTION_PENALTY = 0.35
HEALTH_SHORTAGE_PENALTY = 5

EDU_TARGET_BASE = 30
EDU_PER_RESEARCH_LEVEL = 8
EDU_STABILITY_FACTOR = 0.3
EDU_SHORTAGE_PENALTY = 4

POLLUTION_TARGET_BASE = 10
POLLUTION_PER_INDUSTRY_LEVEL = 10
POLLUTION_PER_MINING_LEVEL = 6
POLLUTION_MITIGATION_PER_POWER_LEVEL = 4
POLLUTION_MITIGATION_PER_RESEARCH_LEVEL = 3
POLLUTION_SHORTAGE_SPIKE = 3

INDEX_ADJUST_RATE = 0.25

# Population policy defaults
POP_RETAIN_PERCENT_DEFAULT = 0.7
POP_EXPORT_CAP_DEFAULT = 50
POP_POLICY_PRIORITY_MULTIPLIERS = {
    "keep_local": 0.5,
    "balanced": 1.0,
    "export_heavy": 1.5,
}

# Default population per colony level (for migrations/backfill)
POPULATION_DEFAULT_BY_LEVEL = {
    0: 50,
    1: 200,
    2: 500,
    3: 1000,
}
